language: node_js

node_js:
- "lts/*"

notifications:
  email: false

before_install:
- rustup update
- rustup target add wasm32-unknown-unknown --toolchain nightly
- rustc +nightly --target wasm32-unknown-unknown -O hello.rs

install:
- npm install

script:
- npm run build && npm run test:coveralls

cache:
  directories:
  - "node_modules"

matrix:
  include:
  - language: rust

    rust:
    - nightly
    script:
    - rustup target add wasm32-unknown-unknown
    - rustup default nightly
