language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

  install:
    - rustup update
    - rustup target add wasm32-unknown-unknown --toolchain nightly
    - rustc +nightly --target wasm32-unknown-unknown -O hello.rs
    - npm install

  script:
    - npm run build
